name: Kernel Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc
          sudo apt-get install -y gcc-12 g++-12  # Install GCC version 12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
          sudo update-alternatives --set gcc /usr/bin/gcc-12
          sudo update-alternatives --set g++ /usr/bin/g++-12
          gcc --version  # Verify the GCC version

      - name: Set up build environment
        run: |
          export KBUILD_BUILD_USER="DEQUR-01(EQ)"
          export KBUILD_BUILD_HOST="github-actions"

      - name: Create output directory
        run: mkdir -p out

      - name: Build kernel
        run: |
          make O=out ARCH=arm64 defconfig
          make -j$(nproc) O=out ARCH=arm64
